### PR TITLE
Refactored constants, added token format validation, flexible parameter parsing, and Jest unit testing.

### PR DESCRIPTION
**Pull request by 0xCaponte**
Added:
- constants.js to centralize the various constants used
- jwtValidator.js for format and algorithm validation of the JWT token. Only well formatted HS256 should pass
- argsParser.js for flexible argument parsing and improved help message by using Yargs
- index.test.js to replace test.js using jest and the new argument-flags
- Added all the git contributors to the package.json (ordered alphabetically)
- Added VSCode folders to the gitignore

Tests (with Jest):
- Unit-Tests for the JwtValidator
- The logic in test.js is now in index.test.js

Comments:
- Jest is still working on the ES integration, that is why --experimental-vm-modules is used for testing
- A refactoring of the index.js might make a more complete test of the "whole" logic easier/faster.

### CODE REVIEW

**Comment by 0xCaponte** [comment]
Updating the README.md for the new argument format would also be needed: 
` jwt-cracker -t <token> [-a <alphabet>] [--max <maxLength>]`

**Review by lmammino — APPROVED** [review]
Thanks for the awesome contribution! 🤟🏽

**Comment by lmammino** [comment]
The tests seems to be breaking, could you please have a look at them? @0xCaponte ?

**Comment by 0xCaponte** [comment]
I had a wrong class name. Now all tests pass locally.

**Pull request merged**
